# -*- coding: utf-8 -*-
"""
御风面板 (bt_simple) 完整多语言词库构建器
生成 zh-CN, zh-TW, en, fr, de, it 全套语言包
"""

import os
import re
import json

BASE_LANG_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../web/static/language"))
SRC_DIR = os.path.join(BASE_LANG_DIR, "zh-CN")

from generate_languages import to_traditional_chinese, LANGUAGES

# 常用专业词汇对照词典 (中文 -> 英文, 法文, 德文, 意大利文)
CORE_PHRASES = {
    # 常用操作与状态
    "操作成功": {"en": "Operation successful", "fr": "Opération réussie", "de": "Vorgang erfolgreich", "it": "Operazione riuscita"},
    "操作失败": {"en": "Operation failed", "fr": "Opération échouée", "de": "Vorgang fehlgeschlagen", "it": "Operazione non riuscita"},
    "添加成功": {"en": "Added successfully", "fr": "Ajouté avec succès", "de": "Erfolgreich hinzugefügt", "it": "Aggiunto con successo"},
    "添加失败": {"en": "Failed to add", "fr": "Échec de l'ajout", "de": "Hinzufügen fehlgeschlagen", "it": "Impossibile aggiungere"},
    "删除成功": {"en": "Deleted successfully", "fr": "Supprimé avec succès", "de": "Erfolgreich gelöscht", "it": "Eliminato con successo"},
    "删除失败": {"en": "Failed to delete", "fr": "Échec de la suppression", "de": "Löschen fehlgeschlagen", "it": "Impossibile eliminare"},
    "设置成功": {"en": "Settings saved", "fr": "Paramètres enregistrés", "de": "Einstellungen gespeichert", "it": "Impostazioni salvate"},
    "设置失败": {"en": "Failed to save settings", "fr": "Échec de l'enregistrement des paramètres", "de": "Speichern fehlgeschlagen", "it": "Impossibile salvare le impostazioni"},
    "修改成功": {"en": "Modified successfully", "fr": "Modifié avec succès", "de": "Erfolgreich geändert", "it": "Modificato con successo"},
    "修改失败": {"en": "Failed to modify", "fr": "Échec de la modification", "de": "Ändern fehlgeschlagen", "it": "Impossibile modificare"},
    "保存成功": {"en": "Saved successfully", "fr": "Enregistré avec succès", "de": "Erfolgreich gespeichert", "it": "Salvato con successo"},
    "保存失败": {"en": "Failed to save", "fr": "Échec de l'enregistrement", "de": "Speichern fehlgeschlagen", "it": "Impossibile salvare"},
    "更新成功": {"en": "Updated successfully", "fr": "Mis à jour avec succès", "de": "Erfolgreich aktualisiert", "it": "Aggiornato con successo"},
    "更新失败": {"en": "Failed to update", "fr": "Échec de la mise à jour", "de": "Aktualisierung fehlgeschlagen", "it": "Impossibile aggiornare"},
    "正在处理,请稍候...": {"en": "Processing, please wait...", "fr": "Traitement en cours, veuillez patienter...", "de": "Wird verarbeitet, bitte warten...", "it": "Elaborazione in corso, attendere..."},
    "正在保存,请稍候...": {"en": "Saving, please wait...", "fr": "Enregistrement, veuillez patienter...", "de": "Wird gespeichert, bitte warten...", "it": "Salvataggio in corso, attendere..."},
    "正在读取,请稍候...": {"en": "Reading, please wait...", "fr": "Lecture en cours, veuillez patienter...", "de": "Wird gelesen, bitte warten...", "it": "Lettura in corso, attendere..."},
    "正在获取,请稍候...": {"en": "Fetching, please wait...", "fr": "Récupération, veuillez patienter...", "de": "Wird abgerufen, bitte warten...", "it": "Recupero in corso, attendere..."},
    "正在删除,请稍候...": {"en": "Deleting, please wait...", "fr": "Suppression en cours, veuillez patienter...", "de": "Wird gelöscht, bitte warten...", "it": "Eliminazione in corso, attendere..."},
    "正在添加,请稍候...": {"en": "Adding, please wait...", "fr": "Ajout en cours, veuillez patienter...", "de": "Wird hinzugefügt, bitte warten...", "it": "Aggiunta in corso, attendere..."},
    "保存": {"en": "Save", "fr": "Enregistrer", "de": "Speichern", "it": "Salva"},
    "修改": {"en": "Modify", "fr": "Modifier", "de": "Ändern", "it": "Modifica"},
    "删除": {"en": "Delete", "fr": "Supprimer", "de": "Löschen", "it": "Elimina"},
    "添加": {"en": "Add", "fr": "Ajouter", "de": "Hinzufügen", "it": "Aggiungi"},
    "取消": {"en": "Cancel", "fr": "Annuler", "de": "Abbrechen", "it": "Annulla"},
    "确定": {"en": "Confirm", "fr": "Confirmer", "de": "Bestätigen", "it": "Conferma"},
    "关闭": {"en": "Close", "fr": "Fermer", "de": "Schließen", "it": "Chiudi"},
    "刷新": {"en": "Refresh", "fr": "Actualiser", "de": "Aktualisieren", "it": "Aggiorna"},
    "提交": {"en": "Submit", "fr": "Soumettre", "de": "Absenden", "it": "Invia"},
    "执行": {"en": "Execute", "fr": "Exécuter", "de": "Ausführen", "it": "Esegui"},
    "操作": {"en": "Action", "fr": "Action", "de": "Aktion", "it": "Azione"},
    "状态": {"en": "Status", "fr": "Statut", "de": "Status", "it": "Stato"},
    "说明": {"en": "Description", "fr": "Description", "de": "Beschreibung", "it": "Descrizione"},
    "名称": {"en": "Name", "fr": "Nom", "de": "Name", "it": "Nome"},
    "类型": {"en": "Type", "fr": "Type", "de": "Typ", "it": "Tipo"},
    "时间": {"en": "Time", "fr": "Heure", "de": "Zeit", "it": "Ora"},
    "大小": {"en": "Size", "fr": "Taille", "de": "Größe", "it": "Dimensione"},
    "权限": {"en": "Permissions", "fr": "Permissions", "de": "Berechtigungen", "it": "Permessi"},
    "所有者": {"en": "Owner", "fr": "Propriétaire", "de": "Eigentümer", "it": "Proprietario"},
    "提示": {"en": "Tip", "fr": "Conseil", "de": "Hinweis", "it": "Suggerimento"},
    "警告": {"en": "Warning", "fr": "Avertissement", "de": "Warnung", "it": "Avviso"},
    "帮助": {"en": "Help", "fr": "Aide", "de": "Hilfe", "it": "Aiuto"},
    "返回": {"en": "Back", "fr": "Retour", "de": "Zurück", "it": "Indietro"},
    "列表": {"en": "List", "fr": "Liste", "de": "Liste", "it": "Elenco"},
    "全部": {"en": "All", "fr": "Tout", "de": "Alle", "it": "Tutto"},
    "搜索": {"en": "Search", "fr": "Rechercher", "de": "Suchen", "it": "Cerca"},
    "登录": {"en": "Login", "fr": "Connexion", "de": "Anmelden", "it": "Accedi"},
    "退出": {"en": "Logout", "fr": "Déconnexion", "de": "Abmelden", "it": "Disconnetti"},
    "首页": {"en": "Dashboard", "fr": "Tableau de bord", "de": "Dashboard", "it": "Dashboard"},
    "网站": {"en": "Websites", "fr": "Sites Web", "de": "Websites", "it": "Siti Web"},
    "数据库": {"en": "Databases", "fr": "Bases de données", "de": "Datenbanken", "it": "Database"},
    "安全": {"en": "Security", "fr": "Sécurité", "de": "Sicherheit", "it": "Sicurezza"},
    "文件": {"en": "Files", "fr": "Fichiers", "de": "Dateien", "it": "File"},
    "计划任务": {"en": "Cron Tasks", "fr": "Tâches Cron", "de": "Cron-Aufgaben", "it": "Attività Cron"},
    "软件管理": {"en": "Software", "fr": "Logiciels", "de": "Software", "it": "Software"},
    "系统监控": {"en": "Monitoring", "fr": "Surveillance", "de": "Überwachung", "it": "Monitoraggio"},
    "监控": {"en": "Monitoring", "fr": "Surveillance", "de": "Überwachung", "it": "Monitoraggio"},
    "日志": {"en": "Logs", "fr": "Journaux", "de": "Protokolle", "it": "Log"},
    "面板设置": {"en": "Settings", "fr": "Paramètres", "de": "Einstellungen", "it": "Impostazioni"},
    "启用": {"en": "Enable", "fr": "Activer", "de": "Aktivieren", "it": "Abilita"},
    "停用": {"en": "Disable", "fr": "Désactiver", "de": "Deaktivieren", "it": "Disabilita"},
    "开启": {"en": "Turn on", "fr": "Activer", "de": "Einschalten", "it": "Attiva"},
    "启动": {"en": "Start", "fr": "Démarrer", "de": "Starten", "it": "Avvia"},
    "停止": {"en": "Stop", "fr": "Arrêter", "de": "Stoppen", "it": "Arresta"},
    "重启": {"en": "Restart", "fr": "Redémarrer", "de": "Neustarten", "it": "Riavvia"},
    "重载": {"en": "Reload", "fr": "Recharger", "de": "Neu laden", "it": "Ricarica"},
    "安装": {"en": "Install", "fr": "Installer", "de": "Installieren", "it": "Installa"},
    "卸载": {"en": "Uninstall", "fr": "Désinstaller", "de": "Deinstallieren", "it": "Disinstalla"},
    "备份": {"en": "Backup", "fr": "Sauvegarde", "de": "Sicherung", "it": "Backup"},
    "恢复": {"en": "Restore", "fr": "Restaurer", "de": "Wiederherstellen", "it": "Ripristina"},
    "导入": {"en": "Import", "fr": "Importer", "de": "Importieren", "it": "Importa"},
    "导出": {"en": "Export", "fr": "Exporter", "de": "Exportieren", "it": "Esporta"},
    "下载": {"en": "Download", "fr": "Télécharger", "de": "Herunterladen", "it": "Scarica"},
    "上传": {"en": "Upload", "fr": "Téléverser", "de": "Hochladen", "it": "Carica"},
    "复制": {"en": "Copy", "fr": "Copier", "de": "Kopieren", "it": "Copia"},
    "剪切": {"en": "Cut", "fr": "Couper", "de": "Ausschneiden", "it": "Taglia"},
    "压缩": {"en": "Compress", "fr": "Compresser", "de": "Komprimieren", "it": "Comprimi"},
    "解压": {"en": "Extract", "fr": "Extraire", "de": "Entpacken", "it": "Estrai"},
    "重命名": {"en": "Rename", "fr": "Renommer", "de": "Umbenennen", "it": "Rinomina"},
    "终端": {"en": "Terminal", "fr": "Terminal", "de": "Terminal", "it": "Terminale"},
    "清空": {"en": "Clear", "fr": "Vider", "de": "Leeren", "it": "Svuota"},
    "知道了": {"en": "Got it", "fr": "Compris", "de": "Verstanden", "it": "Ho capito"},
    "用户名": {"en": "Username", "fr": "Nom d'utilisateur", "de": "Benutzername", "it": "Nome utente"},
    "密码": {"en": "Password", "fr": "Mot de passe", "de": "Passwort", "it": "Password"},
    "验证码": {"en": "Captcha", "fr": "Code de vérification", "de": "Captcha", "it": "Captcha"},
    "域名": {"en": "Domain", "fr": "Domaine", "de": "Domain", "it": "Dominio"},
    "端口": {"en": "Port", "fr": "Port", "de": "Port", "it": "Porta"},
    "根目录": {"en": "Root Directory", "fr": "Répertoire racine", "de": "Stammverzeichnis", "it": "Directory principale"},
    "备注": {"en": "Remark", "fr": "Remarque", "de": "Bemerkung", "it": "Nota"},
    "内存": {"en": "Memory", "fr": "Mémoire", "de": "Arbeitsspeicher", "it": "Memoria"},
    "磁盘": {"en": "Disk", "fr": "Disque", "de": "Festplatte", "it": "Disco"},
    "上行": {"en": "Upload", "fr": "Montant", "de": "Upload", "it": "Upload"},
    "下行": {"en": "Download", "fr": "Descendant", "de": "Download", "it": "Download"},
    "网络": {"en": "Network", "fr": "Réseau", "de": "Netzwerk", "it": "Rete"},
    "进程": {"en": "Process", "fr": "Processus", "de": "Prozess", "it": "Processo"},
    "线程": {"en": "Thread", "fr": "Fil d'exécution", "de": "Thread", "it": "Thread"},
    "连接": {"en": "Connections", "fr": "Connexions", "de": "Verbindungen", "it": "Connessioni"},
    "协议": {"en": "Protocol", "fr": "Protocole", "de": "Protokoll", "it": "Protocollo"},
    "放行": {"en": "Allow", "fr": "Autoriser", "de": "Zulassen", "it": "Consenti"},
    "屏蔽": {"en": "Block", "fr": "Bloquer", "de": "Blockieren", "it": "Blocca"},
    "回收站": {"en": "Recycle Bin", "fr": "Corbeille", "de": "Papierkorb", "it": "Cestino"},
    "版本": {"en": "Version", "fr": "Version", "de": "Version", "it": "Versione"},
    "检查更新": {"en": "Check Update", "fr": "Vérifier les mises à jour", "de": "Auf Updates prüfen", "it": "Controlla aggiornamenti"},
    "立即更新": {"en": "Update Now", "fr": "Mettre à jour maintenant", "de": "Jetzt aktualisieren", "it": "Aggiorna ora"},
    "御风面板": {"en": "YuFeng Panel", "fr": "Panneau YuFeng", "de": "YuFeng Panel", "it": "Pannello YuFeng"},
    "Linux面板": {"en": "Linux Panel", "fr": "Panneau Linux", "de": "Linux Panel", "it": "Pannello Linux"},
}

print(f"Loaded core translation phrases ({len(CORE_PHRASES)}).")
